

-- Retrieving Reports Generated by a Specific Librarian
SELECT * FROM Report WHERE LibrarianID = [LibrarianID];


-- Finding All Reservations Made by a Specific Patron:
SELECT R.* FROM Reservation R JOIN Patron P ON R.PatronID = P.ID WHERE P.ID = [PatronID];


-- Listing Books in a Particular Reservation:
SELECT B.* FROM Book B JOIN BookReservation BR ON B.ID = BR.BookID WHERE BR.ReservationID = [ReservationID];


-- Details of Transactions (Borrowed Books) by a Patron:
SELECT T.*, B.Title FROM Transaction T JOIN Book B ON T.BookID = B.ID WHERE T.PatronID = [PatronID];


-- Notifications Sent to a Specific Patron:
SELECT * FROM Notification WHERE PatronID = [PatronID];


-- Books Reserved by a Patron:
SELECT B.* FROM Book B 
JOIN BookReservation BR ON B.ID = BR.BookID 
JOIN Reservation R ON BR.ReservationID = R.ID 
WHERE R.PatronID = [PatronID];


-- All Patrons Who Have Borrowed a Specific Book:
SELECT P.* FROM Patron P 
JOIN Transaction T ON P.ID = T.PatronID 
WHERE T.BookID = [BookID];


-- All Books a Patron is Interested In or Has Borrowed:
SELECT B.* FROM Book B 
JOIN PatronBook PB ON B.ID = PB.BookID 
WHERE PB.PatronID = [PatronID];


-- All Librarians Who Have Handled a Specific Reservation:
SELECT L.* FROM Librarian L 
JOIN Reservation R ON L.ID = R.LibrarianID 
WHERE R.ID = [ReservationID];


-- Updating a Book's Status When It's Returned:
UPDATE Book SET Status = 'Available' WHERE ID = [BookID];


